### ISSUE TITLE
Review for the Final group capstone: set up the Kanban board

### ISSUE THREAD

**Issue by jose-Abel** [Final-Capstone-Elite-Group/RentUrTechBackend#16]
## Hello,

This is our PR for the Kanban project. **We are a group of 5 people.**

The link for our Kanban project it's in:
https://github.com/orgs/Final-Capstone-Elite-Group/projects/1

For our Kanban Board we did the following:
- Create cards based on [the project requirements](https://github.com/microverseinc/curriculum-final-capstone/blob/main/projects/business_requirements.md). 
- Each card has a descriptive title, the number of points in the [Xpt] prefix and a description of the task.

![image](https://user-images.githubusercontent.com/43800831/171513937-f29458d0-b791-4107-ac63-859d80112172.png)

**Comment by vichuge** [comment]
Hi dear student, 

Good job so far!
You still need to work on some issues to prepare your project for the final evaluation, but you are almost there!

![mario_ladders](https://user-images.githubusercontent.com/20563252/121369265-4e418880-c901-11eb-848c-1eff06d5a4cf.gif)

## Suggested changes

- [ ] I could observe you got 2 diff columns for "In review". To have the project more according to the requests, please use only one "In review" column. Please, check this image as a guide to change the columns more according to what is expected.
![image](https://user-images.githubusercontent.com/20563252/171516493-6b27c601-3ca3-4b0e-b397-2129afb55820.png)


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by JohnFTitor** [comment]
## Hello

This is our PR for the Kanban project. **We are a group of 5 people.**

The link for our Kanban project it's in:
https://github.com/orgs/Final-Capstone-Elite-Group/projects/1

For our Kanban Board we did the following:
- Create cards based on [the project requirements](https://github.com/microverseinc/curriculum-final-capstone/blob/main/projects/business_requirements.md). 
- Each card has a descriptive title, the number of points in the [Xpt] prefix and a description of the task.

![image](https://user-images.githubusercontent.com/74314917/171516870-06e9e2b2-fe31-40a4-8bb1-1b5875989471.png)

**Comment by MuriloRoque** [comment]
Hi @jose-Abel, @JohnFTitor, 

In my opinion, your project is complete!

Good luck! 🎉 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
